travis:
  secure:
    BINSTAR_TOKEN: tykTAVbx+Sgj8AfJMzWJSfGdgQIql8d2NuWWvPv0ihwIFetIXJhnzeaYIju+k6RbS/4Mb6dTaWH5/gzsfwOj3DuielnDdAaGHU+ZxvN59sr0Oe4Oh1+rxopl8ZtJWKUWL8jzyXf1wSMacIUzvRMCPYerQ2BDw1JPdiZK+3k1AiTAdh61JGsUAiDV5ggwfU/7Pf0OIkck1jYoV0/eLZH+gLQkVeOu4+VllN7moajq8QSxomrHCN/xIhlIA52UKdqlhaCmoUkcuFRO3t3UqwnmEHMlpwPCgQAaMIIQEBv57zHSBMve4+AodSB8es9g9JEFEyMpi8KgO9lxteFJZ/KDS8LtsI/p6Tm9npyoBAyvc/Py3U36TGFxr4iRZHHO6RxIfjgjSPiPQM8AbAWiEUUFwhFdXu1SnGDheHN+y0PS3Uw3e8GFuRUVDeS8bivqmg8uhsaGOQxbMqjdZVr+zZyv+kEVHXGCY1dM8Fri82Atrq4ebd/kgRLLVxnkJvueTBpfNBoe3LmJT3SOKPxSM6d5lyOBl+l1JCqkQQIfGHYc8baytPnoSnDs1/kIOcAsUL/+icE0G7tcjlUKuAOW2mudE84qvtNo5VA8nA/GGAzbR60Mq0UTF0rO1xNGzVXMCMLchcns5FPjhaG7IAZ8VYoIaY5SOpCCOkf9FPXfRuADFSw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
